export const styles = {
  root: {
    height: "100vh",
    width: "100vw",
    display: "flex",
    alignItems: "stretch",
    backgroundColor: "#E6EE9C",
    flexDirection: "column",
  },
  webCamParentPanel: {
    width: "100%",
    backgroundColor: "#C5CAE9",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    margin: 0,
    padding: 0,
    gap: 0,
  },
  webCamPanel: {
    display: "flex",
    height: "100%",
    backgroundColor: "#FFF59D",
    justifyContent: "center",
    alignItems: "center",
    margin: 0,
    padding: 0,
    gap: 0,
  },
  settingPanel: {
    display: "flex",
    height: "100%",
    backgroundColor: "#FFF59D",
    justifyContent: "center",
    alignItems: "center",
    margin: 0,
    padding: 0,
    gap: 0,
  },
  faceMaskPanel: {
    display: "flex",
    backgroundColor: "#BBDEFB",
    justifyContent: "space-evenly",
    alignItems: "center",
    margin: 0,
    padding: 0,
    gap: 0,
  },
  faceMaskContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: 0,
    padding: 0,
    gap: 0,
    flexDirection: "column",
  },
  webCamStackItem: {
    position: "absolute",
    top: 0,
    left: 0,
    marginLeft: "auto",
  },
};
